### ISSUE TITLE
Fingerprint and Camera not working on AOSP 8.1

### ISSUE THREAD

**Issue by eckR** [sonyxperiadev/device-sony-nile#28]
After building and flashing AOSP 8.1 following the instructions on Sony developer world, there was no option for adding a fingerprint in the security settings.

Furthermore the camera app does not open. A message appears: no camera device found.

Otherwise 8.1 would be a perfect daily driver :)

Device: Xperia XA2 - H3113

**Comment by jerpelea** [comment]
please use the bug tracker
