### ISSUE TITLE
(not an issue) Is it possible to add LDAC coding for XA2 Ultra

### ISSUE THREAD

**Issue by kaixinzheng** [sonyxperiadev/device-sony-nile#92]
We all know Sony license LDAC coding for android, but it's a little shame that it didn't  support on Sony's own phone - XA2 Ultra for marketing purpose. Is it possible to add LDAC on the next software update?

**Comment by MarijnS95** [comment]
I think this can be closed now. `libldac` comes [with the AOSP source](https://android.googlesource.com/platform/external/libldac) and is automatically compiled in as part of VNDK, which is enabled on all devices now (and could also be enabled for all devices on Android 9, afaik). On older branches and API levels that do not have VNDK enabled, `PRODUCT_PACKAGES := libldacBT_abr libldacBT_enc` could be added to include the libraries.
